<?php

namespace Database\Seeders;

use App\Enumerators\SubscriptionEnumerator;
use App\Models\Subscription;
use Illuminate\Database\Seeder;

class SubscriptionSeeder extends Seeder
{
    public function run(): void
    {
        Subscription::create([
            'name' => SubscriptionEnumerator::CORE,
            'title' => 'Standard',
            'type' => SubscriptionEnumerator::TYPE_CORE,
            'description' => 'Enjoy essential features and tools with our "Basic Ease" subscription. Perfect for startups and small businesses, this plan provides access to core functionalities that streamline your operations. Stay organized, manage employees, and track time effortlessly. Upgrade your efficiency with the "Basic Ease" subscription.',
            'amount' => 200,
            'features' => json_encode(json_decode(json_encode([
                'Payroll Auto-Generation' => 'title',
                'Salary Computation' => true,
                'Unlimited Allowances' => true,
                'Unlimited Commissions' => true,
                'Unlimited Deductions' => true,
                'Leaves Calculation' => true,
                'SSS Contribution' => true,
                'Philhealth Contribution' => true,
                'Pagibig Contribution' => true,
                'Withheld Tax' => true,
                'Taxables & Non-taxables' => true,
                'Special Payrolls' => true,
                '13th Month Payrolls' => true,
                'Final Pay' => true,
                'Holidays' => true,
                'Late Deduction' => false,
                'Undertime Deduction' => false,
                'Absences Deduction' => false,
                'Overtime Pay' => false,
                'Employee Management' => 'title',
                'Salary Breakdown' => true,
                'Timesheet Management' => false,
                'Shifts Management' => false,
                'Time and Attendance' => 'title',
                'Time tracking' => false,
                'Overtime Setting' => false,
                'Grace Period Setting' => false,
                'QR Code Time Tracking' => false,
                'Biometrics Time Tracking' => false,
                'Time Correction' => false,
                'Disbursement Management' => 'title',
                'Bulk Disbursement' => false,
                'Scheduled Disbursement' => false,
                'Instapay' => false,
                'Pesonet' => false,
                'Reports and Analytics' => 'title',
                'Yearly Payroll Expenses' => true,
                'Monthly Payroll Expenses' => true,
                'Employee Earnings' => true,
                'Attendance Analysis' => false,
                'Disbursement Analysis' => false,
            ]), true)),
        ]);

        Subscription::create([
            'name' => SubscriptionEnumerator::CORE_TIME,
            'title' => 'Premium',
            'type' => SubscriptionEnumerator::TYPE_BUNDLE,
            'description' => 'Elevate your workforce management with the "Time and Attendance 49" subscription. Unlock advanced time tracking and attendance features that empower your business to optimize productivity. Seamlessly manage employee schedules, monitor attendance trends, and ensure accurate payroll. Elevate your team\'s efficiency with the "Time and Attendance 49" subscription.',
            'amount' => 250,
            'features' => json_encode([
                'Payroll Auto-Generation' => 'title',
                'Salary Computation' => true,
                'Unlimited Allowances' => true,
                'Unlimited Commissions' => true,
                'Unlimited Deductions' => true,
                'Leaves Calculation' => true,
                'SSS Contribution' => true,
                'Philhealth Contribution' => true,
                'Pagibig Contribution' => true,
                'Withheld Tax' => true,
                'Taxables & Non-taxables' => true,
                'Special Payrolls' => true,
                '13th Month Payrolls' => true,
                'Final Pay' => true,
                'Holidays' => true,
                'Late Deduction' => true,
                'Undertime Deduction' => true,
                'Absences Deduction' => true,
                'Overtime Pay' => true,
                'Employee Management' => 'title',
                'Salary Breakdown' => true,
                'Timesheet Management' => true,
                'Shifts Management' => true,
                'Time and Attendance' => 'title',
                'Time tracking' => true,
                'Overtime Setting' => true,
                'Grace Period Setting' => true,
                'QR Code Time Tracking' => true,
                'Biometrics Time Tracking' => true,
                'Time Correction' => true,
                'Disbursement Management' => 'title',
                'Bulk Disbursement' => false,
                'Scheduled Disbursement' => false,
                'Instapay' => false,
                'Pesonet' => false,
                'Reports and Analytics' => 'title',
                'Yearly Payroll Expenses' => true,
                'Monthly Payroll Expenses' => true,
                'Employee Earnings' => true,
                'Attendance Analysis' => true,
                'Disbursement Analysis' => false,
            ]),
        ]);

        Subscription::create([
            'name' => SubscriptionEnumerator::CORE_TIME_DISBURSE,
            'title' => 'Ultimate',
            'type' => SubscriptionEnumerator::TYPE_BUNDLE,
            'description' => "Simplify payroll processes and enhance financial efficiency with the 'Auto-Disburse' subscription. Say goodbye to manual disbursements and embrace automated salary payments. Seamlessly distribute salaries, benefits, and incentives to your employees with precision and ease. Enhance your payroll management with the streamlined 'Auto-Disburse' subscription.",
            'amount' => 300,
            'features' => json_encode([
                'Payroll Auto-Generation' => 'title',
                'Salary Computation' => true,
                'Unlimited Allowances' => true,
                'Unlimited Commissions' => true,
                'Unlimited Deductions' => true,
                'Leaves Calculation' => true,
                'SSS Contribution' => true,
                'Philhealth Contribution' => true,
                'Pagibig Contribution' => true,
                'Withheld Tax' => true,
                'Taxables & Non-taxables' => true,
                'Special Payrolls' => true,
                '13th Month Payrolls' => true,
                'Final Pay' => true,
                'Holidays' => true,
                'Late Deduction' => true,
                'Undertime Deduction' => true,
                'Absences Deduction' => true,
                'Overtime Pay' => true,
                'Employee Management' => 'title',
                'Salary Breakdown' => true,
                'Timesheet Management' => true,
                'Shifts Management' => true,
                'Time and Attendance' => 'title',
                'Time tracking' => true,
                'Overtime Setting' => true,
                'Grace Period Setting' => true,
                'QR Code Time Tracking' => true,
                'Biometrics Time Tracking' => true,
                'Time Correction' => true,
                'Disbursement Management' => 'title',
                'Bulk Disbursement' => true,
                'Scheduled Disbursement' => true,
                'Instapay' => true,
                'Pesonet' => true,
                'Reports and Analytics' => 'title',
                'Yearly Payroll Expenses' => true,
                'Monthly Payroll Expenses' => true,
                'Employee Earnings' => true,
                'Attendance Analysis' => true,
                'Disbursement Analysis' => true,
            ]),
        ]);

        Subscription::create([
            'name' => 'trial-core-plus-time-and-attendance',
            'title' => 'Trial',
            'type' => 'trial',
            'description' => 'Elevate your workforce management with the "Time and Attendance 49" subscription. Unlock advanced time tracking and attendance features that empower your business to optimize productivity. Seamlessly manage employee schedules, monitor attendance trends, and ensure accurate payroll. Elevate your team\'s efficiency with the "Time and Attendance 49" subscription.',
            'amount' => 250,
            'features' => json_encode([
                'Payroll Auto-Generation' => 'title',
                'Salary Computation' => true,
                'Unlimited Allowances' => true,
                'Unlimited Commissions' => true,
                'Unlimited Deductions' => true,
                'Leaves Calculation' => true,
                'SSS Contribution' => true,
                'Philhealth Contribution' => true,
                'Pagibig Contribution' => true,
                'Withheld Tax' => true,
                'Taxables & Non-taxables' => true,
                'Special Payrolls' => true,
                '13th Month Payrolls' => true,
                'Final Pay' => true,
                'Holidays' => true,
                'Late Deduction' => true,
                'Undertime Deduction' => true,
                'Absences Deduction' => true,
                'Overtime Pay' => true,
                'Employee Management' => 'title',
                'Salary Breakdown' => true,
                'Timesheet Management' => true,
                'Shifts Management' => true,
                'Time and Attendance' => 'title',
                'Time tracking' => true,
                'Overtime Setting' => true,
                'Grace Period Setting' => true,
                'QR Code Time Tracking' => true,
                'Biometrics Time Tracking' => true,
                'Time Correction' => true,
                'Disbursement Management' => 'title',
                'Bulk Disbursement' => false,
                'Scheduled Disbursement' => false,
                'Instapay' => false,
                'Pesonet' => false,
                'Reports and Analytics' => 'title',
                'Yearly Payroll Expenses' => true,
                'Monthly Payroll Expenses' => true,
                'Employee Earnings' => true,
                'Attendance Analysis' => true,
                'Disbursement Analysis' => false,
            ]),
        ]);
    }
}
